// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';

export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS";
export const USER_VERIFY_FAIL = "USER_VERIFY_FAIL";

// USER
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_FAIL = 'USER_ADD_FAIL';

export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAIL = 'USER_GET_FAIL';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const REQUEST_NEW_PASSWORD_SUCCESS = 'REQUEST_NEW_PASSWORD_SUCCESS';
export const REQUEST_NEW_PASSWORD_FAIL = 'REQUEST_NEW_PASSWORD_FAIL';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';


// CHATROOM
export const CHATROOM_LIST_REQUEST = 'CHATROOM_LIST_REQUEST';
export const CHATROOM_LIST_SUCCESS = 'CHATROOM_LIST_SUCCESS';
export const CHATROOM_LIST_FAIL = 'CHATROOM_LIST_FAIL';

export const CHATROOM_CREATE_REQUEST = 'CHATROOM_CREATE_REQUEST';
export const CHATROOM_CREATE_SUCCESS = 'CHATROOM_CREATE_SUCCESS';
export const CHATROOM_CREATE_FAIL = 'CHATROOM_CREATE_FAIL';

export const ADD_PARTICIPANTS_SUCCESS = 'ADD_PARTICIPANTS_SUCCESS';
export const ADD_PARTICIPANTS_FAIL = 'ADD_PARTICIPANTS_FAIL';

// MESSAGE
export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL';

export const MESSAGE_CREATE_REQUEST = 'MESSAGE_CREATE_REQUEST';
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESS';
export const MESSAGE_CREATE_FAIL = 'MESSAGE_CREATE_FAIL';

export const REACT_TO_MESSAGE_REQUEST = 'REACT_TO_MESSAGE_REQUEST';
export const REACT_TO_MESSAGE_SUCCESS = 'REACT_TO_MESSAGE_SUCCESS';
export const REACT_TO_MESSAGE_FAIL = 'REACT_TO_MESSAGE_FAIL';

// SUBSCRIPTION
export const ADD_SUBSCRIPTION_REQUEST = 'ADD_SUBSCRIPTION_REQUEST';
export const ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS';
export const ADD_SUBSCRIPTION_FAIL = 'ADD_SUBSCRIPTION_FAIL';

export const DELETE_SUBSCRIPTION_REQUEST = 'DELETE_SUBSCRIPTION_REQUEST';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_FAIL = 'DELETE_SUBSCRIPTION_FAIL';

// WORSHIP
export const GET_LATEST_WORSHIP_REQUEST = 'GET_LATEST_WORSHIP_REQUEST';
export const GET_LATEST_WORSHIP_SUCCESS = 'GET_LATEST_WORSHIP_SUCCESS';
export const GET_LATEST_WORSHIP_FAIL = 'GET_LATEST_WORSHIP_FAIL';

export const UPDATE_LATEST_WORSHIP_REQUEST = 'UPDATE_LATEST_WORSHIP_REQUEST';
export const UPDATE_LATEST_WORSHIP_SUCCESS = 'UPDATE_LATEST_WORSHIP_SUCCESS';
export const UPDATE_LATEST_WORSHIP_FAIL = 'UPDATE_LATEST_WORSHIP_FAIL';

// BLOGS
export const BLOGS_LIST_REQUEST = 'BLOGS_LIST_REQUEST';
export const BLOGS_LIST_SUCCESS = 'BLOGS_LIST_SUCCESS';
export const BLOGS_LIST_FAIL = 'BLOGS_LIST_FAIL';

export const BLOG_GET_ID_REQUEST = 'BLOG_GET_ID_REQUEST';
export const BLOG_GET_ID_SUCCESS = 'BLOG_GET_ID_SUCCESS';
export const BLOG_GET_ID_FAIL = 'BLOG_GET_ID_FAIL';

export const BLOG_VIDEO_UPLOAD_REQUEST = 'BLOG_VIDEO_UPLOAD_REQUEST';
export const BLOG_VIDEO_UPLOAD_SUCCESS = 'BLOG_VIDEO_UPLOAD_SUCCESS';
export const BLOG_VIDEO_UPLOAD_FAIL = 'BLOG_VIDEO_UPLOAD_FAIL';

export const BLOG_VIDEO_DEL_REQUEST = 'BLOG_VIDEO_DEL_REQUEST';
export const BLOG_VIDEO_DEL_SUCCESS = 'BLOG_VIDEO_DEL_SUCCESS';
export const BLOG_VIDEO_DEL_FAIL = 'BLOG_VIDEO_DEL_FAIL';

// BIBLE
export const GET_BIBLES_REQUEST = 'GET_BIBLES_REQUEST';
export const GET_BIBLES_SUCCESS = 'GET_BIBLES_SUCCESS';
export const GET_BIBLES_FAIL = 'GET_BIBLES_FAIL';

export const GET_BIBLE_VERSE_REQUEST = 'GET_BIBLE_VERSES_REQUEST';
export const GET_BIBLE_VERSE_SUCCESS = 'GET_BIBLE_VERSES_SUCCESS';
export const GET_BIBLE_VERSE_FAIL = 'GET_BIBLE_VERSES_FAIL';

// JOURNALS
// 📘 Get all journals (paginated)
export const GET_JOURNALS_SUCCESS = 'GET_JOURNALS_SUCCESS';
export const GET_JOURNALS_FAIL = 'GET_JOURNALS_FAIL';

// 📘 Get single journal by ID
export const GET_JOURNAL_BY_ID_SUCCESS = 'GET_JOURNAL_BY_ID_SUCCESS';
export const GET_JOURNAL_BY_ID_FAIL = 'GET_JOURNAL_BY_ID_FAIL';

// 📝 Create journal
export const CREATE_JOURNAL_SUCCESS = 'CREATE_JOURNAL_SUCCESS';
export const CREATE_JOURNAL_FAIL = 'CREATE_JOURNAL_FAIL';

// 🔁 Update journal
export const UPDATE_JOURNAL_SUCCESS = 'UPDATE_JOURNAL_SUCCESS';
export const UPDATE_JOURNAL_FAIL = 'UPDATE_JOURNAL_FAIL';

// ❌ Delete journal
export const DELETE_JOURNAL_SUCCESS = 'DELETE_JOURNAL_SUCCESS';
export const DELETE_JOURNAL_FAIL = 'DELETE_JOURNAL_FAIL';

// Albums Types
export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST';
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS';
export const ALBUM_LIST_FAIL = 'ALBUM_LIST_FAIL';

export const ALBUM_CREATE_REQUEST = 'ALBUM_CREATE_REQUEST';
export const ALBUM_CREATE_SUCCESS = 'ALBUM_CREATE_SUCCESS';
export const ALBUM_CREATE_FAIL = 'ALBUM_CREATE_FAIL';

export const ALBUM_UPDATE_REQUEST = 'ALBUM_UPDATE_REQUEST';
export const ALBUM_UPDATE_SUCCESS = 'ALBUM_UPDATE_SUCCESS';
export const ALBUM_UPDATE_FAIL = 'ALBUM_UPDATE_FAIL';

export const ALBUM_DELETE_REQUEST = 'ALBUM_DELETE_REQUEST'; 
export const ALBUM_DELETE_SUCCESS = 'ALBUM_DELETE_SUCCESS';
export const ALBUM_DELETE_FAIL = 'ALBUM_DELETE_FAIL';

export const ALBUM_GET_REQUEST = 'ALBUM_GET_REQUEST';
export const ALBUM_GET_SUCCESS = 'ALBUM_GET_SUCCESS';
export const ALBUM_GET_FAIL = 'ALBUM_GET_FAIL';

// Music Types
export const MUSIC_LIST_REQUEST = 'MUSIC_LIST_REQUEST';
export const MUSIC_LIST_SUCCESS = 'MUSIC_LIST_SUCCESS';
export const MUSIC_LIST_FAIL = 'MUSIC_LIST_FAIL';

export const MUSIC_CREATE_REQUEST = 'MUSIC_CREATE_REQUEST';
export const MUSIC_CREATE_SUCCESS = 'MUSIC_CREATE_SUCCESS';
export const MUSIC_CREATE_FAIL = 'MUSIC_CREATE_FAIL';

export const MUSIC_UPDATE_REQUEST = 'MUSIC_UPDATE_REQUEST';
export const MUSIC_UPDATE_SUCCESS = 'MUSIC_UPDATE_SUCCESS';
export const MUSIC_UPDATE_FAIL = 'MUSIC_UPDATE_FAIL';

export const MUSIC_DELETE_REQUEST = 'MUSIC_DELETE_REQUEST';
export const MUSIC_DELETE_SUCCESS = 'MUSIC_DELETE_SUCCESS';
export const MUSIC_DELETE_FAIL = 'MUSIC_DELETE_FAIL';

export const MUSIC_GET_REQUEST = 'MUSIC_GET_REQUEST';
export const MUSIC_GET_SUCCESS = 'MUSIC_GET_SUCCESS';
export const MUSIC_GET_FAIL = 'MUSIC_GET_FAIL';

// Playlist Types
export const PLAYLIST_LIST_REQUEST = 'PLAYLIST_LIST_REQUEST';
export const PLAYLIST_LIST_SUCCESS = 'PLAYLIST_LIST_SUCCESS';
export const PLAYLIST_LIST_FAIL = 'PLAYLIST_LIST_FAIL';

export const PLAYLIST_CREATE_REQUEST = 'PLAYLIST_CREATE_REQUEST';
export const PLAYLIST_CREATE_SUCCESS = 'PLAYLIST_CREATE_SUCCESS';
export const PLAYLIST_CREATE_FAIL = 'PLAYLIST_CREATE_FAIL';

export const PLAYLIST_UPDATE_REQUEST = 'PLAYLIST_UPDATE_REQUEST';
export const PLAYLIST_UPDATE_SUCCESS = 'PLAYLIST_UPDATE_SUCCESS';
export const PLAYLIST_UPDATE_FAIL = 'PLAYLIST_UPDATE_FAIL';

export const PLAYLIST_DELETE_REQUEST = 'PLAYLIST_DELETE_REQUEST';
export const PLAYLIST_DELETE_SUCCESS = 'PLAYLIST_DELETE_SUCCESS';
export const PLAYLIST_DELETE_FAIL = 'PLAYLIST_DELETE_FAIL';

export const PLAYLIST_GET_REQUEST = 'PLAYLIST_GET_REQUEST';
export const PLAYLIST_GET_SUCCESS = 'PLAYLIST_GET_SUCCESS';
export const PLAYLIST_GET_FAIL = 'PLAYLIST_GET_FAIL';

export const PLAYLIST_ADD_MUSIC_REQUEST = 'PLAYLIST_ADD_MUSIC_REQUEST';
export const PLAYLIST_ADD_MUSIC_SUCCESS = 'PLAYLIST_ADD_MUSIC_SUCCESS';
export const PLAYLIST_ADD_MUSIC_FAIL = 'PLAYLIST_ADD_MUSIC_FAIL';

export const PLAYLIST_REMOVE_MUSIC_REQUEST = 'PLAYLIST_REMOVE_MUSIC_REQUEST';
export const PLAYLIST_REMOVE_MUSIC_SUCCESS = 'PLAYLIST_REMOVE_MUSIC_SUCCESS';
export const PLAYLIST_REMOVE_MUSIC_FAIL = 'PLAYLIST_REMOVE_MUSIC_FAIL';

// 🎵 Music Player Types
export const SET_TRACK_LIST = 'SET_TRACK_LIST';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_VOLUME = 'SET_VOLUME';
export const PLAY_NEXT_TRACK = 'PLAY_NEXT_TRACK';
export const PLAY_PREVIOUS_TRACK = 'PLAY_PREVIOUS_TRACK';

// Follow Types
export const FOLLOWERS_LIST_REQUEST = 'FOLLOWERS_LIST_REQUEST';
export const FOLLOWERS_LIST_SUCCESS = 'FOLLOWERS_LIST_SUCCESS';
export const FOLLOWERS_LIST_FAIL = 'FOLLOWERS_LIST_FAIL';

export const FOLLOWING_LIST_REQUEST = 'FOLLOWING_LIST_REQUEST';
export const FOLLOWING_LIST_SUCCESS = 'FOLLOWING_LIST_SUCCESS';
export const FOLLOWING_LIST_FAIL = 'FOLLOWING_LIST_FAIL';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL';

// Post Types
export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_FAIL = 'POST_LIST_FAIL';

export const POST_GET_REQUEST = 'POST_GET_REQUEST';
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';
export const POST_GET_FAIL = 'POST_GET_FAIL';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_ADD_COMMENT_REQUEST = 'POST_ADD_COMMENT_REQUEST';
export const POST_ADD_COMMENT_SUCCESS = 'POST_ADD_COMMENT_SUCCESS';
export const POST_ADD_COMMENT_FAIL = 'POST_ADD_COMMENT_FAIL';

export const POST_COMMENTS_LIST_REQUEST = 'POST_COMMENTS_LIST_REQUEST';
export const POST_COMMENTS_LIST_SUCCESS = 'POST_COMMENTS_LIST_SUCCESS';
export const POST_COMMENTS_LIST_FAIL = 'POST_COMMENTS_LIST_FAIL';

export const COMMENT_ADD_REPLY_REQUEST = 'COMMENT_ADD_REPLY_REQUEST';
export const COMMENT_ADD_REPLY_SUCCESS = 'COMMENT_ADD_REPLY_SUCCESS';
export const COMMENT_ADD_REPLY_FAIL = 'COMMENT_ADD_REPLY_FAIL';

export const COMMENT_REPLIES_LIST_REQUEST = 'COMMENT_REPLIES_LIST_REQUEST';
export const COMMENT_REPLIES_LIST_SUCCESS = 'COMMENT_REPLIES_LIST_SUCCESS';
export const COMMENT_REPLIES_LIST_FAIL = 'COMMENT_REPLIES_LIST_FAIL';

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const SHARE_POST_REQUEST = 'SHARE_POST_REQUEST';
export const SHARE_POST_SUCCESS = 'SHARE_POST_SUCCESS';
export const SHARE_POST_FAIL = 'SHARE_POST_FAIL';

export const POST_REACT_REQUEST = 'POST_REACT_REQUEST';
export const POST_REACT_SUCCESS = 'POST_REACT_SUCCESS';
export const POST_REACT_FAIL = 'POST_REACT_FAIL';

export const SET_POST = 'SET_POST';

// Notification Types
export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';











